[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://vale-rv-park.netlify.app/*"
  to = "https://valervpark.com/:splat"
  status = 301
  force = true
